### ISSUE TITLE
Update ktor version to 1.0.0

### ISSUE THREAD

**Issue by juhiken** [zensum/ktor-prometheus-feature#6]
Hi,

Could you please update the project to ktor 1.0.0.
`io.ktor.pipeline.PipelineContext` is deprecated and `io.ktor.util.pipeline.PipelineContext` is the new.

Thanks,
Krisztian

**Comment by mantono** [comment]
Hello Krisztian! We will look into it shortly. Probably about time to update Kotlin to 1.3 and coroutines to stable version as well.

**Comment by mantono** [comment]
@juhiken You can try this `implementation 'com.github.zensum:ktor-prometheus-feature:2bb93010c5'` I haven't had time to test it, but it compiles at least. I'll close this issue for now, but please let us know if it does not work properly.
